services:
  postgres:
    container_name: postgres-ScootTrack
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ScootTrack
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ScootTrack
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-ScootTrack
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
networks:
  ScootTrack:
    driver: bridge
volumes:
  postgres:
    driver: local