spring:
  datasource:
    url: jdbc:postgresql://baza-scootrack.pl:5432/ScootTrack
    username: superUser
    password: superPassword
  mail:
    host: mail-server-scootrack.pl
    port: 1025
    username: superUser
    password: superPassword

application:
  security:
    jwt:
      secret-key: ZXMKQBBFCLH0ZPAHWN4YGVEGER5NUKD7FGD2321SADA213123DASDGFGFDGBNHJHGF
      expiration: 8640000
  mailing:
    frontend:
      activation-url: https://scoottrack.pl/activate-account